import type { NutritionCheck } from "@/types/nutrition";

export const nutritionChecks: NutritionCheck[] = [
  {
    id: "nutrition-2026-05-21",
    date: "2026-05-21",
    targetCalories: 2850,
    estimatedCalories: 2780,
    targetProteinGrams: 165,
    estimatedProteinGrams: 158,
    waterLiters: 3.1,
    adherencePercent: 88,
    digestion: "good",
    dayType: "training",
    notes: "Buen reparto de proteína.",
    pendingFields: [],
  },
  {
    id: "nutrition-2026-05-23",
    date: "2026-05-23",
    targetCalories: 3000,
    estimatedCalories: 3180,
    targetProteinGrams: 165,
    estimatedProteinGrams: 171,
    waterLiters: 2.7,
    adherencePercent: 82,
    digestion: "normal",
    dayType: "high-carb",
    notes: "Carga alta antes del WOD largo.",
    pendingFields: [],
  },
  {
    id: "nutrition-2026-05-25",
    date: "2026-05-25",
    targetCalories: 2600,
    estimatedCalories: 2520,
    targetProteinGrams: 165,
    estimatedProteinGrams: 162,
    waterLiters: 3.4,
    adherencePercent: 91,
    digestion: "good",
    dayType: "rest",
    notes: "Día limpio y fácil de sostener.",
    pendingFields: [],
  },
];
