import { createEmptyMuscleSummary } from "@/lib/selectors/training";
import type { TrainingSession } from "@/types/training";

const baseSummary = createEmptyMuscleSummary();

export const trainingSessions: TrainingSession[] = [
  {
    id: "ts-2026-05-20",
    date: "2026-05-20",
    reportedAt: "2026-05-20",
    dateConfidence: "inferred",
    dateRule: "inferred",
    source: "manual",
    status: "completed",
    title: "HYROX: motor y trineo",
    type: "hyrox",
    subtypes: ["engine", "running", "lower_body"],
    durationMinutes: 72,
    rpe: 8,
    location: "box",
    objective: "Sostener ritmo alto con fatiga local en piernas.",
    rawText: "HYROX motor y trineo: 4 rondas de 1 km carrera y 25 m empuje de trineo pesado.",
    blocks: [
      {
        id: "block-1",
        name: "Intervalos con fatiga",
        format: "intervals",
        roundsPlanned: 4,
        roundsCompleted: 4,
        restSeconds: 120,
        exercises: [
          {
            name: "Carrera",
            canonicalName: "Run",
            distanceMeters: 1000,
            movementPattern: "run",
            intensity: "high",
            muscleLoad: [
              { muscle: "quadriceps", role: "primary", load: 70 },
              { muscle: "calves", role: "secondary", load: 60 },
            ],
          },
          {
            name: "Empuje de trineo",
            canonicalName: "Sled Push",
            distanceMeters: 25,
            movementPattern: "push",
            intensity: "high",
            muscleLoad: [
              { muscle: "quadriceps", role: "primary", load: 90 },
              { muscle: "glutes", role: "secondary", load: 80 },
            ],
          },
        ],
      },
    ],
    result: { type: "none", score: null },
    sessionMetrics: {
      totalRunMeters: 4000,
      totalBikeMeters: 0,
      totalRowMeters: 0,
      totalSkiMeters: 0,
      totalCalories: null,
      totalExternalLoadKg: null,
      totalBarbellReps: 0,
      totalDumbbellReps: 0,
      totalKettlebellReps: 0,
      totalGymnasticsReps: 0,
      hardSetsEstimate: 8,
      impactScore: 78,
      cardioLoad: 82,
      strengthLoad: 58,
      technicalLoad: 20,
      fatigueCost: 82,
    },
    sessionMuscleSummary: { ...baseSummary, quadriceps: 90, glutes: 80, calves: 60 },
    tags: ["hyrox", "engine", "lower-body"],
    soreness: ["quadriceps", "calves"],
    injuryNotes: null,
    feeling: "7/10",
    notes: "Buen control de respiración. Piernas muy cargadas al final.",
    pendingFields: [],
    dataQuality: "partial",
    importNotes: "Mock adaptado al contrato HybridOSAppInput v1.0.",
  },
  {
    id: "ts-2026-05-24",
    date: "2026-05-24",
    reportedAt: "2026-05-24",
    dateConfidence: "inferred",
    dateRule: "inferred",
    source: "manual",
    status: "completed",
    title: "CrossFit mixto",
    type: "crossfit",
    subtypes: ["amrap", "mixed_modal", "full_body"],
    durationMinutes: 61,
    rpe: 9,
    location: "box",
    objective: "Tolerar alta intensidad con transiciones rápidas.",
    rawText: "AMRAP 18: wall balls 9 kg, toes-to-bar y power clean 60 kg.",
    blocks: [
      {
        id: "block-1",
        name: "WOD",
        format: "amrap",
        timeCapMinutes: 18,
        exercises: [
          {
            name: "Wall balls",
            canonicalName: "Wall Ball",
            reps: 20,
            loadKg: 9,
            movementPattern: "squat",
            intensity: "high",
            muscleLoad: [
              { muscle: "quadriceps", role: "primary", load: 80 },
              { muscle: "shoulders", role: "secondary", load: 70 },
            ],
          },
          {
            name: "Toes-to-bar",
            canonicalName: "Toes-to-Bar",
            reps: 12,
            movementPattern: "core",
            intensity: "high",
            muscleLoad: [
              { muscle: "core", role: "primary", load: 80 },
              { muscle: "lats", role: "secondary", load: 50 },
            ],
          },
          {
            name: "Power clean",
            canonicalName: "Power Clean",
            reps: 8,
            loadKg: 60,
            movementPattern: "hinge",
            intensity: "high",
            muscleLoad: [
              { muscle: "hamstrings", role: "primary", load: 70 },
              { muscle: "upperBack", role: "secondary", load: 60 },
            ],
          },
        ],
      },
    ],
    result: { type: "partial", score: null, notes: "Rondas exactas pendientes." },
    sessionMetrics: {
      totalRunMeters: 0,
      totalBikeMeters: 0,
      totalRowMeters: 0,
      totalSkiMeters: 0,
      totalCalories: null,
      totalExternalLoadKg: null,
      totalBarbellReps: 8,
      totalDumbbellReps: 0,
      totalKettlebellReps: 0,
      totalGymnasticsReps: 12,
      hardSetsEstimate: null,
      impactScore: 72,
      cardioLoad: 76,
      strengthLoad: 70,
      technicalLoad: 55,
      fatigueCost: 88,
    },
    sessionMuscleSummary: {
      ...baseSummary,
      quadriceps: 80,
      shoulders: 70,
      core: 80,
      lats: 50,
      hamstrings: 70,
      upperBack: 60,
    },
    tags: ["crossfit", "metcon", "high-intensity"],
    soreness: ["quadriceps", "core", "shoulders"],
    injuryNotes: null,
    feeling: "6/10",
    notes: "Sesión dura. Buen pacing hasta el minuto 14.",
    pendingFields: ["Resultado exacto"],
    dataQuality: "partial",
    importNotes: "Mock adaptado al contrato HybridOSAppInput v1.0.",
  },
];
